# ruff.toml
line-length = 100
target-version = "py310"

# Skip non-code / generated stuff
extend-exclude = [
  "build",
  "dist",
  ".venv",
  "*.egg-info",
  "userdata"
]

[format]
# Formatter settings
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
# Keep this set reasonably strict but not noisy
select = ["E", "F", "I", "UP", "B", "C4"]
# Long lines often happen in SQL/templates/log lines; ignore for now
ignore = ["E501"]

[lint.per-file-ignores]
# __init__ files often re-export symbols
"**/__init__.py" = ["F401", "F403"]

[lint.isort]
known-first-party = ["automic_bootstrap"]
combine-as-imports = true
